### ISSUE TITLE
Add different subject(development) quiz

### ISSUE THREAD

**Issue by Suryansh1720001** [Suryansh1720001/Developer-Quiz#3]

**Comment by Interstellar07** [comment]
Please assign this issue to me

**Comment by Interstellar07** [comment]
I can work on this issue, please assign this to me.

**Comment by Suryansh1720001** [comment]
Hello @Interstellar07 
Ok, go for it. 
Star this repo and Follow me on GitHub @Suryansh1720001

**Comment by Interstellar07** [comment]
Alright, thanks

**Comment by Interstellar07** [comment]
I have initiated a PR for this issue, Kindly check it.

**Comment by Suryansh1720001** [comment]
Completed #5
